server:
  port: 2222

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.130.10.185:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    preferIpAddress: true
